package generator

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/accented-ai/pgtofu/internal/util"
)

type Options struct {
	OutputDir              string
	StartVersion           int
	TransactionMode        TransactionMode
	IncludeComments        bool
	Idempotent             bool
	GenerateDownMigrations bool
	MaxOperationsPerFile   int
	PreviewMode            bool
}

type TransactionMode string

const (
	TransactionModeAuto   TransactionMode = "auto"
	TransactionModeAlways TransactionMode = "always"
	TransactionModeNever  TransactionMode = "never"
)

func DefaultOptions() *Options {
	return &Options{
		OutputDir:              DefaultOutputDir,
		StartVersion:           DefaultStartVersion,
		TransactionMode:        TransactionModeAuto,
		IncludeComments:        true,
		Idempotent:             true,
		GenerateDownMigrations: true,
		MaxOperationsPerFile:   DefaultMaxOpsPerFile,
		PreviewMode:            false,
	}
}

func (o *Options) Validate() error {
	if o == nil {
		return errors.New("options cannot be nil")
	}

	var errs []error

	if o.OutputDir == "" {
		errs = append(errs, errors.New("output directory cannot be empty"))
	}

	if o.StartVersion < 1 {
		errs = append(errs, fmt.Errorf("start version must be >= 1, got %d", o.StartVersion))
	}

	if o.MaxOperationsPerFile < 1 {
		errs = append(
			errs,
			fmt.Errorf("max operations per file must be >= 1, got %d", o.MaxOperationsPerFile),
		)
	}

	switch o.TransactionMode {
	case TransactionModeAuto, TransactionModeAlways, TransactionModeNever:
	default:
		errs = append(
			errs,
			fmt.Errorf(
				"invalid transaction mode: %s (must be auto, always, or never)",
				o.TransactionMode,
			),
		)
	}

	if len(errs) > 0 {
		return util.WrapError("invalid options", errors.Join(errs...))
	}

	return nil
}

type MigrationFile struct {
	Version     int
	Description string
	Direction   Direction
	FileName    string
	Content     string
}

type Direction string

const (
	DirectionUp   Direction = "up"
	DirectionDown Direction = "down"
)

type MigrationPair struct {
	Version     int
	Description string
	UpFile      *MigrationFile
	DownFile    *MigrationFile
}

type GenerateResult struct {
	Migrations     []MigrationPair
	Warnings       []string
	FilesGenerated int
}

func (gr *GenerateResult) Summary() string {
	var sb strings.Builder

	sb.WriteString("Migration Generation Summary\n")
	sb.WriteString("============================\n\n")

	if len(gr.Migrations) == 0 {
		sb.WriteString("No migrations generated.\n")
		return sb.String()
	}

	fmt.Fprintf(&sb, "Migrations Generated: %d\n", len(gr.Migrations))
	fmt.Fprintf(&sb, "Files Created: %d\n", gr.FilesGenerated)

	if len(gr.Warnings) > 0 {
		fmt.Fprintf(&sb, "\nWarnings: %d\n", len(gr.Warnings))

		for _, warning := range gr.Warnings {
			fmt.Fprintf(&sb, "  - %s\n", warning)
		}
	}

	sb.WriteString("\nMigration Files:\n")

	for _, migration := range gr.Migrations {
		if migration.UpFile != nil {
			fmt.Fprintf(&sb, "  %s\n", migration.UpFile.FileName)
		}

		if migration.DownFile != nil {
			fmt.Fprintf(&sb, "  %s\n", migration.DownFile.FileName)
		}
	}

	return sb.String()
}

type migrationHeader struct {
	Version     int
	Description string
	Direction   Direction
	Generated   time.Time
	Changes     []string
}

func (mh *migrationHeader) String() string {
	var sb strings.Builder

	sb.WriteString("-- =====================================================\n")
	fmt.Fprintf(&sb, "-- Migration: %06d_%s.%s.sql\n", mh.Version, mh.Description, mh.Direction)
	fmt.Fprintf(&sb, "-- Generated: %s\n", mh.Generated.Format(time.RFC3339))
	sb.WriteString("-- Generated by pgtofu\n")
	sb.WriteString("-- =====================================================\n")

	if len(mh.Changes) > 0 {
		sb.WriteString("--\n-- Changes:\n")

		for _, change := range mh.Changes {
			fmt.Fprintf(&sb, "--   %s\n", change)
		}

		sb.WriteString("--\n")
	}

	sb.WriteString("-- =====================================================\n\n")

	return sb.String()
}

type DDLStatement struct {
	SQL         string
	Description string
	IsUnsafe    bool
	RequiresTx  bool
	CannotUseTx bool
}
